#!/bin/bash
set -a
#-------------------------------------------------------------------------------
# Nek5000 config
#-------------------------------------------------------------------------------

# source path 
#NEK_SOURCE_ROOT="$HOME/Nek5000" 

#NEK_SOURCE_ROOT="$smallcompute/Nek5000_3d" 
#NEK_SOURCE_ROOT="$HOME/workstation/git/nek_cylindrical/Nek5000" 
#NEK_SOURCE_ROOT="$HOME/workstation/git/nek_cylindrical/Nek5000_ifpgll" 
NEK_SOURCE_ROOT="$HOME/workstation/git/density_variation/Nek5000" 

# Fortran/C compiler
FC="mpif90"
CC="mpicc"

# config options (set to "?" to get a list)
#PPLIST="" 

#-------------------------------------------------------------------------------
# WHAT FOLLOWS ARE OPTIONAL SETTINGS
#-------------------------------------------------------------------------------

# optional compiler flags
FFLAGS="-I./src_inc -mcmodel=medium -g -fbacktrace"
#CFLAGS=""

# optional linking flags
# USR_LFLAGS="-L./ -lparpack_MPI-intel_rst -larpack_intel_rst"
USR_LFLAGS="-L/usr/lib -lparpack -larpack -llapack"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
FRM="frame.o frame_usr.o io_tools.o mntrlog.o mntrtmr.o rprm.o io_tools_block.o mntrlog_block.o mntrtmr_block.o rprm_block.o math_tools.o"            # KTH Framework tools
F3D="solve_f3d.o solvep_f3d.o weak_lapl_cyl.o solver_f3d.o frame_f3d.o"                # Fourier 3D solver
FSF="fs_ale.o fs_sort.o fs_sort_mp.o fs_global_surf.o frame_fs.o localfilter.o"        # Free Surface Motion
ARN="arn_arp.o arn_usr.o arn_arp_io.o arn_cmath.o tstepper.o conht_tools.o"            # Arnoldi
CHKP="chkpoint.o chkpt_mstp.o"                                                         # Checkpointing
LSM="lsm.o lsm_heat.o clsm.o clsm_corr.o lsm_zhoge.o"                                  # Level Set Method
STT="stat.o stat_IO.o stat_usr.o"                                                      # Statistics
MAP="map2D.o map2D_usr.o"                                                              # Mapping tools   
PRC="fast_reset.o h1mg_reset.o"                                                        # Preconditioner reset
MATF="wrapper_lapack.o matf_krylov.o matrix_functions.o"                               # Matrix functions
CYL="frame_cyl.o cylindrical_subs.o cylindrical_plan.o cylindrical_fast.o cylindrical_solver.o cylindrical_conduct.o cylindrical_h1mg.o" # Cylindrical formulation
USR+="$FRM $FSF $CHKP $LSM wrapper_lapack.o full_mass.o kopriva.o generic_subs.o density_transport.o"
#echo $USR
#USR="frame.o mntrlog_block.o mntrlog.o mntrtmr_block.o mntrtmr.o rprm_block.o rprm.o"
#USR+="io_tools.o io_tools_block.o" 
#USR+="solve_f3d.o solvep_f3d.o weak_lapl_cyl.o solver_f3d.o frame_f3d.o"


# MPI (default 1) 
#MPI=0

# profiling (default 1)
#PROFILING=0

# VisIt in situ (default 0)
#VISIT=1
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true


###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
: ${NEK_SOURCE_ROOT:="$HOME/Nek5000"}
echo "using source path: $NEK_SOURCE_ROOT"
VERMAKENEK="19.0.1"
set +a -e
$NEK_SOURCE_ROOT/bin/nekconfig $@
if [[ $1 != "clean" ]]; then
 $NEK_SOURCE_ROOT/bin/nekconfig -build-dep
 set -o pipefail
 make -j4 2>&1 | tee -a build.log
 set +o pipefail
fi
